#!/bin/bash

basepath=$HOME/bin

if test "$#" -eq 0 ; then
	echo "Usage: $0 name [cmd]"
	echo "cmd = {start|stop|restart}, default = restart"
	exit 1
fi

if test -z "$2" ; then
	cmd="restart"
else
	cmd=$2
fi

tunbasepath="$basepath/tun_"
tunfilepath=$tunbasepath$1

if ! test -f $tunbasepath$1 ; then
	echo "Tunnel $1 undefined, available tunnels are:"
	echo `ls $tunbasepath* | grep -v .pid | replace $tunbasepath ""`
	exit 1
fi

pidfilepath="$tunfilepath.pid"

case $cmd in
"start")
	if test -f $pidfilepath ; then
		pid=`cat $pidfilepath`
		echo "Tunnel $1 already exists, pid = $pid"
		exit 1
	fi

	bash $tunfilepath
	tuncmd=`head -n 1 $tunfilepath`
	echo `ps x | grep -F "$tuncmd" | grep -F -v "grep" | awk '{print $1}'` >$pidfilepath
;;
"stop")
	if ! test -f $pidfilepath ; then
		exit 1
	fi

	kill -9 `cat $pidfilepath`
	rm $pidfilepath	
;;
"restart")
	tunnel $1 stop
	tunnel $1 start
;;
*)
	echo "Unknown cmd, available cmds are: start, stop, restart"
	exit 1
;;
esac