#!/bin/sh

# Prerequisites:
# * export JAVA_HOME=$HOME/bin/jdk
# * export PATH=$PATH:$HOME/bin/jdk/bin:$HOME/bin/jdk/jre/bin
# * different JDK versions unpacked in $HOME/bin/jdk1.x*

if [ -z "$1" ] || (test "$1" -ne "7" && test "$1" -ne "8") ; then
    echo "Usage: $0 7|8"
    exit 1
fi

basepath=$HOME/bin

jdkname=`ls $basepath | grep jdk1.$1 | tail -1`

if [ -z "$jdkname" ] ; then
    echo "jdk1.$1 not found"
    exit 1
fi

rm $basepath/jdk
ln -s $basepath/$jdkname $basepath/jdk

echo "Using $jdkname"
